# permissions for end users to edit eventstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: eventstore-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dt-operator
    app.kubernetes.io/part-of: dt-operator
    app.kubernetes.io/managed-by: kustomize
  name: eventstore-editor-role
rules:
- apiGroups:
  - core.digitaltwin
  resources:
  - eventstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.digitaltwin
  resources:
  - eventstores/status
  verbs:
  - get
