# permissions for end users to view messagebrokers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: messagebroker-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dt-operator
    app.kubernetes.io/part-of: dt-operator
    app.kubernetes.io/managed-by: kustomize
  name: messagebroker-viewer-role
rules:
- apiGroups:
  - core.digitaltwin
  resources:
  - messagebrokers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.digitaltwin
  resources:
  - messagebrokers/status
  verbs:
  - get
