# permissions for end users to view twincomponents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: twincomponent-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dt-operator
    app.kubernetes.io/part-of: dt-operator
    app.kubernetes.io/managed-by: kustomize
  name: twincomponent-viewer-role
rules:
- apiGroups:
  - dtd.digitaltwin
  resources:
  - twincomponents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dtd.digitaltwin
  resources:
  - twincomponents/status
  verbs:
  - get
