---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.digitaltwin
  resources:
  - eventstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.digitaltwin
  resources:
  - eventstores/finalizers
  verbs:
  - update
- apiGroups:
  - core.digitaltwin
  resources:
  - eventstores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.digitaltwin
  resources:
  - messagebrokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.digitaltwin
  resources:
  - messagebrokers/finalizers
  verbs:
  - update
- apiGroups:
  - core.digitaltwin
  resources:
  - messagebrokers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.digitaltwin
  resources:
  - messaginggateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.digitaltwin
  resources:
  - messaginggateways/finalizers
  verbs:
  - update
- apiGroups:
  - core.digitaltwin
  resources:
  - messaginggateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dtd.digitaltwin
  resources:
  - twincomponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dtd.digitaltwin
  resources:
  - twincomponents/finalizers
  verbs:
  - update
- apiGroups:
  - dtd.digitaltwin
  resources:
  - twincomponents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dtd.digitaltwin
  resources:
  - twinenums
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dtd.digitaltwin
  resources:
  - twinenums/finalizers
  verbs:
  - update
- apiGroups:
  - dtd.digitaltwin
  resources:
  - twinenums/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dtd.digitaltwin
  resources:
  - twininstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dtd.digitaltwin
  resources:
  - twininstances/finalizers
  verbs:
  - update
- apiGroups:
  - dtd.digitaltwin
  resources:
  - twininstances/status
  verbs:
  - get
  - patch
  - update
