# permissions for end users to view twinservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: twinservice-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dt-operator
    app.kubernetes.io/part-of: dt-operator
    app.kubernetes.io/managed-by: kustomize
  name: twinservice-viewer-role
rules:
- apiGroups:
  - dtdl.digitaltwin
  resources:
  - twinservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dtdl.digitaltwin
  resources:
  - twinservices/status
  verbs:
  - get
