# permissions for end users to edit twinservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: twinservice-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dt-operator
    app.kubernetes.io/part-of: dt-operator
    app.kubernetes.io/managed-by: kustomize
  name: twinservice-editor-role
rules:
- apiGroups:
  - dtd.digitaltwin
  resources:
  - twinservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dtd.digitaltwin
  resources:
  - twinservices/status
  verbs:
  - get
