# permissions for end users to edit twinclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: twinclass-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dt-operator
    app.kubernetes.io/part-of: dt-operator
    app.kubernetes.io/managed-by: kustomize
  name: twinclass-editor-role
rules:
- apiGroups:
  - dtdl.digitaltwin
  resources:
  - twinclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dtdl.digitaltwin
  resources:
  - twinclasses/status
  verbs:
  - get
