apiVersion: v1
kind: Namespace
metadata:
  name: core
  labels:
    app.kubernetes.io/name: core
    app.kubernetes.io/version: "0.0.1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: integration
  labels:
    app.kubernetes.io/name: integration
    app.kubernetes.io/version: "0.0.1"