# Exemplos
# Trabalho Neto - Usar como use case

apiVersion: dtd.digitaltwin/v0
kind: TwinInstance
metadata:
  name: factory-twin-01
spec:
  name: factory-twin-01
  component:
    name: factory
---
apiVersion: dtd.digitaltwin/v0
kind: TwinInstance
metadata:
  name: factory-twin-02
spec:
  name: factory-twin-02
  component:
    name: factory
---
apiVersion: dtd.digitaltwin/v0
kind: TwinInstance
metadata:
  name: machine-twin-01
spec:
  name: machine-twin-01
  parentInstance: factory-twin-01
  component:
    name: machine
---
apiVersion: dtd.digitaltwin/v0
kind: TwinInstance
metadata:
  name: machine-twin-02
spec:
  name: machine-twin-02
  parentInstance: factory-twin-02
  component:
    name: machine
  events: # Dado capturado vs operacao interna que venha a gerar um evento
    - filter:
        type: event.machine-01
      sink: factory-twin-01
---
apiVersion: dtd.digitaltwin/v0
kind: TwinInstance
metadata:
  name: temperature-sensor-01
spec:
  name: temperature-sensor-01
  parentInstance: machine-twin-01
  component:
    name: temperature-sensor
  events:
    - sink: machine-twin-01
  template:
    spec:
      containers:
        - name: edge-service
          image: agwermann/manufactoring-service:0.1
          imagePullPolicy: Always
          args: ["http://mqtt-response-handler", "80"]

# Use cases
# Olhar trabalho Neto
# Pai processar o dado do filho
# Filho processa a mensagem antes de armazenar (container do usuário)
# Ser capaz de armazenar histórico de eventos
# Eventos propagar apenas para o pai parte deles
# Eventos propagar apenas para o pai
# Temperature média das válvulas nos pais (aggregate)

---
# Multiple Topics (Parent subscribe to all children)
# ---
# apiVersion: dtd.digitaltwin/v0
# kind: TwinInstance
# metadata:
#   name: pressure-sensor-01
# spec:
#   name: pressure-sensor-01
#   parentInstance: machine-twin-01
#   component:
#     name: pressure-sensor
#   template:
#     spec:
#       containers:
#         - name: edge-service
#           image: agwermann/manufactoring-service:0.1
#           imagePullPolicy: Always
#           args: ["http://mqtt-response-handler", "80"]
# ---
# apiVersion: dtd.digitaltwin/v0
# kind: TwinInstance
# metadata:
#   name: temperature-sensor-02
# spec:
#   name: temperature-sensor-02
#   parentInstance: machine-twin-02
#   component:
#     name: temperature-sensor
#   template:
#     spec:
#       containers:
#         - name: edge-service
#           image: agwermann/manufactoring-service:0.1
#           imagePullPolicy: Always
#           args: ["http://mqtt-response-handler", "80"]
# ---
# apiVersion: dtd.digitaltwin/v0
# kind: TwinInstance
# metadata:
#   name: pressure-sensor-02
# spec:
#   name: pressure-sensor-02
#   parentInstance: machine-twin-02
#   component:
#     name: pressure-sensor
#   template:
#     spec:
#       containers:
#         - name: edge-service
#           image: agwermann/manufactoring-service:0.1
#           imagePullPolicy: Always
#           args: ["http://mqtt-response-handler", "80"]
# ---
