apiVersion: dtd.digitaltwin/v0
kind: TwinEnum
metadata:
  labels:
    app.kubernetes.io/name: twinenum
    app.kubernetes.io/instance: twinenum-sample
    app.kubernetes.io/part-of: dt-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dt-operator
  name: twinenum-sample
spec:
    name: Factory Type
    values:
      - Headquarter
      - Branch
