apiVersion: dtd.digitaltwin/v0
kind: TwinService
metadata:
  labels:
    app.kubernetes.io/name: twinservice
    app.kubernetes.io/instance: twinservice-sample
    app.kubernetes.io/part-of: dt-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dt-operator
  name: twinservice-sample
spec:
  name: TwinServiceName
  dataSource: mqtt
  dataTarget: mqtt
  template:
    spec:
      containers:
          - name: edge-service
            image: dev.local/edge-service:0.1
            imagePullPolicy: Never
            args: ["http://mqtt-response-handler", "80"]